version: '3.8'
services:
  bookmarker-db:
    image: postgres:alpine3.19
    container_name: postgres-01
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"

  bookmarker-api:
    image: qkrdud2002/springbootnextjs:0.6
    container_name: spring_01
    ports:
      - "18080:8080"
    restart: always
    depends_on:
      - bookmarker-db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookmarker-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password